### ISSUE TITLE
Dropping spatial indexes does not remove the luceneIndexes/ data

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb-lucene#36] opened 2014-12-18 08:44 UTC
As noted on issue #35. I can reproduce this reliable on snapshot 2.0.

**Comment by maggiolo00** [comment] 2015-01-20 11:00
Is this yet valid? or is it resolved with 2.0-rc2?

**Comment by maggiolo00** [comment] 2015-09-22 13:02
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Closed by maggiolo00** 2015-09-22 13:02 UTC
Labels: bug
